### ISSUE TITLE
npm shrinkwrap does not work with the current grunt and grunt-contrib-rename

### ISSUE THREAD

**Issue by prantlf** [jasonlam604/grunt-rename-util#7]
Error:

```text
$ npm shrinkwrap --dev
npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v4.7.2
npm ERR! npm  v4.1.1

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: grunt@~0.4.0, required by grunt-contrib-rename@0.0.3
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /media/ferdipr/Dev/carbonfibre/cs.core.ui/main/pkg/CS_CORE_UI.git/npm-debug.log
```

npm-debug.log:

```text
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@4.1.1
3 info using node@v4.7.2
4 info lifecycle cs.core.ui@16.0.0~preshrinkwrap: cs.core.ui@16.0.0
5 silly lifecycle cs.core.ui@16.0.0~preshrinkwrap: no script for preshrinkwrap, continuing
6 info lifecycle cs.core.ui@16.0.0~shrinkwrap: cs.core.ui@16.0.0
7 silly lifecycle cs.core.ui@16.0.0~shrinkwrap: no script for shrinkwrap, continuing
8 verbose stack Error: Problems were encountered
8 verbose stack Please correct and try again.
8 verbose stack peer invalid: grunt@~0.4.0, required by grunt-contrib-rename@0.0.3
8 verbose stack     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:128:15)
8 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
8 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
8 verbose stack     at done (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:132:5)
8 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
8 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:318:20
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
8 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
9 verbose cwd /media/ferdipr/Dev/carbonfibre/cs.core.ui/main/pkg/CS_CORE_UI.git
10 error Linux 4.8.0-34-generic
11 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
12 error node v4.7.2
13 error npm  v4.1.1
14 error Problems were encountered
14 error Please correct and try again.
14 error peer invalid: grunt@~0.4.0, required by grunt-contrib-rename@0.0.3
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

Peer dependency on grunt should be changed from:

```json
  "peerDependencies": {
    "grunt": "~0.4.0"
  }
```

to the version compatible with grunt 1.x, like it is done in `gruntt-contrib-clean`, for example:

```json
  "peerDependencies": {
    "grunt": ">= 0.4.5"
  }
```

**Comment by prantlf** [comment]
Any of PRs #2, #5 or #6 should fix this issue.

**Comment by jasonlam604** [comment]
Fixed btw package has been renamed to grunt-rename-util
